### ISSUE TITLE
Setting hostname in kcadm-wrapper.sh.erb

### ISSUE THREAD

**Issue by negast** [treydock/puppet-module-keycloak#129]
Hello

Is it possible to have an extra variable so we don't have to use localhost in this file?

**Comment by treydock** [comment]
What file are you referring to?

**Comment by negast** [comment]
templates/kcadm-wrapper.sh.erb

from
`  
#!/bin/bash

KCADM="<%= scope['keycloak::install_base'] %>/bin/kcadm.sh"

${KCADM} "$@" --no-config --server http://localhost:<%= scope['keycloak::http_port'] %>/auth --realm master --user <%= scope['keycloak::admin_user'] %> --password <%= scope['keycloak::admin_user_password'] %>`
to
  
`#!/bin/bash

KCADM="<%= scope['keycloak::install_base'] %>/bin/kcadm.sh"

${KCADM} "$@" --no-config --server http://<%= scope['keycloak::admin_host'] %>:<%= scope['keycloak::http_port'] %>/auth --realm master --user <%= scope['keycloak::admin_user'] %> --password <%= scope['keycloak::admin_user_password'] %>`

maybe?

**Comment by treydock** [comment]
Why not use localhost? The intent of kcadm-wrapper.sh was to run that script on the local Keycloak server as a replacement for kcadm.sh. Are you installing it on a remote server?

**Comment by negast** [comment]
It is installed locally but. I think its only bound to a single interface on the server. I could resolve this matter in the hosts file. but it was easier adapting the wrapper file

**Comment by treydock** [comment]
If you used this module to install Keycloak then it should be bound to `0.0.0.0` which is all interfaces including `localhost`.  if Keycloak was not installed with this module then not sure how you're using the wrapper script as it only works with this module.  Did you by chance change `service_bind_address` to something other than `0.0.0.0`?

**Comment by negast** [comment]
Ok I tested again. What you said was correct and the interface is bound to 0.0.0.0. So it should indeed allow localhost. I changed the value in the wrapper script again. And it works now. So there was probably something else wrong or left unconfigured that some1 solved. I'll close the ticket. Thanks for the help
