### ISSUE TITLE
Adding Vagrant VMs for clustered domain mode?

### ISSUE THREAD

**Issue by mattock** [treydock/puppet-module-keycloak#132]
We're working on a Vagrant development environment for Keycloak's clustered domain mode. Right now our code is in a private repository. It consists of
* Two Keycloak instances where one is configured as the domain controller
* Shared database instance
* Load balancer (haproxy) instance

Would you be interested in merging our clustered domain mode Vagrant environment to this project as well?

**Comment by treydock** [comment]
As long as the Vagrant environment uses this puppet module to set things up, then that sort of addition makes sense.  Could create an examples directory with like `examples/vagrant-cluster` directory and put Vagrantfile there so can be a way to see working example.

**Comment by mattock** [comment]
Ok we'll do that. It will use this Puppet module to configure the Keycloak instances of course. We will probably need to touch on the manifests a bit to make it work.

**Comment by treydock** [comment]
Closed via #180
