### ISSUE TITLE
Add support for JGROUPS JDBC_PING when clustered mode enabled

### ISSUE THREAD

**Issue by danifr** [treydock/puppet-module-keycloak#138]
I think this feature will be very useful for those of us who we want to have a keycloak running in a cluster but for whatever reason we cannot use multicast (default protocol used by JGroups to manage the nodes)

I will work on this PR.

**Comment by danifr** [comment]
Some info about JDBC_PING: http://jgroups.org/manual/#_jdbc_ping

> JDBC_PING uses a DB to store information about cluster nodes used for discovery. All cluster nodes are supposed to be able to access the same DB.
> 
> When a node starts, it queries information about existing members from the database, determines the coordinator and then asks the coord to join the cluster. It also inserts information about itself into the table, so others can subsequently find it.

**Comment by danifr** [comment]
A few things:
- Users will still need to open port 7600 if they want they servers to be discoverable by each other. Maybe worthy to add it to the module?
- I took all config.cli commands from https://medium.com/@mickael.gregori/configure-jgroups-to-run-keycloak-in-clustered-mode-8991fd655e74 and I modified the SQL query to make it work with postgresql. Maybe there is room from improvement there. We can discuss it.
- The current config has been tested on Keycloak 7 (and 10 too) with postgresql. It works fine

**Comment by treydock** [comment]
I would just recommend documenting the firewall change. This module doesn't manage the firewall for any of the other ports that might need to be open and firewall configs are something I tend to see being very site specific, especially when how to order the rules comes into play.
