### ISSUE TITLE
Add custom_fragment variable to configure config.cli

### ISSUE THREAD

**Issue by danifr** [treydock/puppet-module-keycloak#141]
I was thinking of adding a `$custom_fragment` variable to this module.
Like the one the apache module has to configure vhosts https://github.com/puppetlabs/puppetlabs-apache/blob/51ce2adcfc231c6a78dda5cc59c2aaf4028bb5bd/manifests/vhost.pp#L1349
This custom fragment will be appended to the config.cli.erb.

Thoughts? I will open a PR if you are OK with the idea.

**Comment by treydock** [comment]
I think something like `$custom_config` would work. My only hesitation with `$custom_fragment` is the word fragment because that's only a valid idea with concat module and no real reason to use concat module here, instead can just deploy a second config file and make it behave like the one provided from this module.  One pattern that is useful is making it two parameters, `custom_config_source` and `custom_config_content` , both being undef and so a site can choose to provide a plain file or content (template).

**Comment by danifr** [comment]
My initial idea was to add something like this to the config.cli.erb:
```
...
<%- if scope['keycloak::custom_config'] -%>
<%= scope['keycloak::custom_config'] %>
<%- end -%>
```

And then people can do:
```
class { 'keycloak':
  ...
  custom_config => epp('apps/keycloak/custom.config'),
  ...
}
```

Also they can pass a simple string and that will work too.

I am not sure about having more than one config.cli files though. This might add complexity since we will need to run https://github.com/treydock/puppet-module-keycloak/blob/master/manifests/config.pp#L66 twice. Also it would make things more difficult to debug, since there are 2 different files changing the config in the standalone.xml.

**Comment by treydock** [comment]
I think what makes the most sense to only execute the jboss CLI once is this:

```puppet
concat { "${keycloak::install_base}/config.cli":
  ...
  notify    => Exec['jboss-cli.sh --file=config.cli']
 }
concat::fragment { 'config.cli-keycloak':
      target => "${keycloak::install_base}/config.cli",
      content => template('keycloak/config.cli.erb'),
      order     => '00',
}
if $custom_config_content or $custom_config_source {
  concat::fragment { 'config.cli-custom':
      target => "${keycloak::install_base}/config.cli",
      content => $custom_config_content,
      source   => $custom_config_source,
      order     => '01',
  }
}
```

This way a site can choose to provide `custom_config_source => 'puppet:///site_modules/profile/keycloak.cli'` or like your example they can provide a epp or erb template via `custom_config_content`.
