### ISSUE TITLE
Turn warnings about smtp_server_password into notices

### ISSUE THREAD

**Issue by Karlinde** [treydock/puppet-module-keycloak#144]
When setting smtp_server_password for a realm, there is a warning being printed to stderr: 
`Warning: Property 'smtp_server_password' is set and Puppet has no way to check current value`
As I understand the code and the discussions in #131 this was done since the keycloak only returns a redacted string of ***'s when checking the current value. So I would assume that the new password value is always being set on each apply.

The issue is that this is being displayed as a warning via stderr rather than a notice. My intended workflow is that I run puppet apply standalone as a cron job once per hour and send an email if anything gets printed to stderr, so this creates quite a lot of noise for something that I can't seem to do anything about.

I would regard this belongs more as a notice than a warning since it's merely informing us that the password value was set, similar to the notices when other resources have been updated with new values.

It looks like the same pattern is used for keycloak_ldap_user_provider and keycloak_identity_provider also, I would imagine the same reasoning could be used there.

Also, thanks for the great work on this module!

**Comment by treydock** [comment]
The way the Puppet code works is the password is not changed on every Puppet run.  It's only changed on creation of a realm or if other properties in the realm are changed.

I will think about if issuing the logs as a notice is appropriate. Have you considered changing your workflow to run puppet apply with --detailed-exitcodes and checking exit core for success/failure?  I think monitoring on stderr is too dependent on modules not producing stderr output, where as --detailed-exitcodes was designed to do exactly what it is you are doing.

FWIW I have a similar approach to Puppet via cron and puppet apply on many of my systems and I just scrape syslog for errors as Puppet logs to syslog. I look at exit code for scripting and look for error messages in syslog.  If for some reason your logs don't end up in syslog but you want them to I use this trick often on other cron jobs:

```
<script> 2>&1 | logger -t <program name>
```

**Comment by Karlinde** [comment]
Thanks for the tip. I'm still new to Puppet, it makes sense to not be dependent on the behaviour of every single module. I can use another workflow instead, so I'll close this issue for now.
