### ISSUE TITLE
Prettify resulting xml files

### ISSUE THREAD

**Issue by kibahop** [treydock/puppet-module-keycloak#205]
When working with the module, something like 'xmllint --format' would make it easier to follow the changes in xml files. This is especially so with augeas edits, where formatting is frequently ugly.

**Comment by treydock** [comment]
My main objection to such a change would be it could likely make a diff between Puppet XML and XML from Keycloak almost impossible to compare.  So far seems like there are no changes that aren't whitespace:

```sh
[root@webdev06 ~]# xmllint --format --pretty 1  /opt/keycloak/standalone/configuration/standalone.xml > /tmp/xml
[root@webdev06 ~]# diff -w -u /opt/keycloak/standalone/configuration/standalone.xml /tmp/xml
--- /opt/keycloak/standalone/configuration/standalone.xml       2021-06-02 16:34:08.000000000 -0400
+++ /tmp/xml    2021-08-23 12:28:23.022434620 -0400
@@ -1,5 +1,4 @@
-<?xml version='1.0' encoding='UTF-8'?>
-
+<?xml version="1.0" encoding="UTF-8"?>
 <server xmlns="urn:jboss:domain:16.0">
     <extensions>
         <extension module="org.jboss.as.clustering.infinispan"/>
```

If you run commands similar to above, are you seeing more changes than whitespace?

**Comment by treydock** [comment]
This is no longer relevant with changes being made to this module to support Keycloak 18+ that uses Quarkus (ie no more XML).
