### ISSUE TITLE
Support for "genreic" properties in types

### ISSUE THREAD

**Issue by mat1010** [treydock/puppet-module-keycloak#222]
Hi,

first of all thank you for this great module. We are already using it to do a general setup of keycloak. We are now planning to use this module to fully configure realms and clients, which we did through the UI so far. Unfortunately we are missing several properties while configuring realms and haven't looked into clients yet.

As an example, following properties are not available within the realm type (but many more available within keycloak that are missing in the module)

* sslRequired
* editUsernameAllowed
* registrationAllowed

Would it be a feasible solution to allow "custom" properties where you can just add whatever you want `kcadm` to use as the **key** part while doing the set? Or would your prefer to define all valid properties within the corresponding type? Or are we missing some option that already allows this?

Thanks in advance

**Comment by treydock** [comment]
I think for realms something like `custom_properties` that accepts key/value pairs would make sense.  There are other types this module manages that are a little more complex in how the JSON data structure is built before sending to Keycloak.  The only real big loss with using a custom properties hash is property validation is lost so it would allow someone to use string `true` when really needs true boolean.  I think my preference is individual new properties for each thing but not opposed to just doing a custom properties type parameter.

**Comment by treydock** [comment]
The `registration_allowed` property does exist, but others I will add along with a way to define custom properties.

**Comment by treydock** [comment]
This was released in v7.12.0.  I added the new properties you listed as direct properties but also added one to accept custom properties.

**Comment by mat1010** [comment]
Thanks a lot for the quick reply and implementation. If you don't mind we'll also open another PR in the next days/weeks with some more properties to allow proper type validation, which is a lot cleaner way, like you already described
