### ISSUE TITLE
Support for partialImport?

### ISSUE THREAD

**Issue by nblock** [treydock/puppet-module-keycloak#229]
First of all, thanks for your module and the effort you put into it!

I was looking for a way to manage groups in Keycloak via Puppet, in particular the creation of groups and the role mappings for a group. This is currently not implemented in the module. Looking further, I discovered the `JSON import` feature of Keycloak that allows to import various settings from a JSON file. This is also support by `kcadm.sh` ([docs](https://www.keycloak.org/docs/latest/server_admin/index.html#importing-a-realm-from-exported-json-file)):

```bash
./bin/kcadm.sh create partialImport -r myrealm -s ifResourceExists=SKIP -o -f ~/mysettings.json 
```

where `mysettings.json` might look something like this:

```json
{
  "id": "myrealm",
  "groups": [
    {
      "name": "group1",
      "path": "/group1",
      "attributes": {},
      "realmRoles": [
        "role1"
      ],
      "clientRoles": {},
      "subGroups": []
    },
    {
      "name": "group2",
      "path": "/group2",
      "attributes": {},
      "realmRoles": [],
      "clientRoles": {},
      "subGroups": []
    }
  ]
}
```

Do you consider the support for `partialImport` as valuable addition to the module? It would allow to bridge the gap between native support for various features in the module and Keycloak's full featureset.

Puppet module version: 7.12.0
Keycloak version: 15.0.2

**Comment by treydock** [comment]
I think utilizing partialImport seems like something this module could do. I don't think it requires a full Ruby type/provider like `keycloak_realm` but rather a defined resource like `keycloak::partial_import` that would look like this:

```puppet
keycloak::partial_import { 'my-groups':
  realm   => 'myrealm',
  source => 'puppet:///site_modules/my_keycloak/groups.json',
}
```

The Puppet code would have to manage the contents of the file the file so it could know when things change and run an `Exec` to do the necessary `kcadm.sh` command.

Let me know if this seems like a viable solution.

**Comment by nblock** [comment]
Looks good! The `partialImport` provides a setting on how to handle existing resources, those are: `FAIL`, `SKIP` and `OVERWRITE`. Those could be added as variable, too.
