### ISSUE TITLE
Support for Debian 11

### ISSUE THREAD

**Issue by vilhelmprytz** [treydock/puppet-module-keycloak#240]
I've tested this module on Debian 11 with Keycloak 16.1.0 and it works with no issues. It would be great if we can list Debian 11 as supported by the module.

**Comment by vilhelmprytz** [comment]
It works fine, except for this warning.

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, unsupported release 11 (file: /etc/puppetlabs/code/environments/production/modules/java/manifests/params.pp, line: 161, column: 20) on node <censored>
```

which I think could be resolved by just editing the `metadata.json`.

**Comment by treydock** [comment]
According to java module commits, Debian 11 support was added as early as v7.1.0 of the java module : https://github.com/puppetlabs/puppetlabs-java/commit/13acbba4c8ee2f049b27d7e7e6853e950c8c9994 - so make sure you have at least v7.1.0 of that module.
