### ISSUE TITLE
Support customUserSearchFilter

### ISSUE THREAD

**Issue by treydock** [treydock/puppet-module-keycloak#25]
@matsadolfsson is customUserSearchFilter part of the LDAP user provider and if so do you have any examples of what that looks like?  Everything in the `config` hash for API objects is pretty much undocumented.

**Comment by matsadolfsson** [comment]
searchScope customUserSearchFilter are part of the ldap user provider configuration.

**Comment by treydock** [comment]
Released in 2.6.0.
