### ISSUE TITLE
The attribute 'login_with_email_allowed' has already been set

### ISSUE THREAD

**Issue by rjemanuele** [treydock/puppet-module-keycloak#251]
When creating a realm with 'login_with_email_allowed' set to true, an error is produced.  This occurs no matter what is set on 'login_with_email_allowed' with the realm if it exists.

```
 Error: Error while evaluating a Resource Statement, Evaluation Error: The attribute 'login_with_email_allowed' has already been set
```

**Comment by treydock** [comment]
That error from Puppet usually means you have that property set twice for a single resource.  I'd look to make sure you only have `login_with_email_allowed` set once for your `keycloak_realm` resource.
