### ISSUE TITLE
support HA deployments

### ISSUE THREAD

**Issue by ikcalB** [treydock/puppet-module-keycloak#253]
since supporting Quarkus, the option to deploy HA clusters has gone away.

Is there a reason for not supporting HA anymore?
(Should still be possible, according to https://www.keycloak.org/server/caching )

**Comment by treydock** [comment]
It's supported, just not exposed as parameter directly.  You have to set `keycloak::configs`:

https://github.com/treydock/puppet-module-keycloak/blob/b61f3f6e855cc4f611c7786b3804bc2c5dfba0b3/manifests/init.pp#L221

The data type supports those cache parameters:

https://github.com/treydock/puppet-module-keycloak/blob/b61f3f6e855cc4f611c7786b3804bc2c5dfba0b3/types/configs.pp#L4-L6

I think only thing missing is configuring the cache config file.

**Comment by treydock** [comment]
So something like this:

```puppet
class { 'keycloak':
  configs => {
    'cache' => 'ispn',
    'cache-config-file' => '<some path to your config or default one>',
    'cache-stack' => 'tcp', # or whatever matches your need
  },
}
```

If you need to push out non-default cache config, would just need to put that into a profile class for now.

**Comment by ikcalB** [comment]
Thanks, I missed that. 

Great module! Also the fast support is appreciated. Have  a nice day :)
