### ISSUE TITLE
KC 19: WARNING: The '--auto-build' option for 'start' command is DEPRECATED

### ISSUE THREAD

**Issue by nblock** [treydock/puppet-module-keycloak#258]
This warning is printed on start when the image is built afresh on Keycloak 19:

> WARNING: The '--auto-build' option for 'start' command is DEPRECATED and no longer needed. When executing the 'start' command, a new server image is automatically built based on the configuration. If you want to disable this behavior and achieve an optimal startup time, use the '--optimized' option instead.

The release notes explain the reason behind this change: https://www.keycloak.org/2022/07/keycloak-1900-released

**Comment by treydock** [comment]
This will be released with v8.3.0 once Github Actions complete
