### ISSUE TITLE
kcadm-wrapper.sh does not quote variables

### ISSUE THREAD

**Issue by Lukas0907** [treydock/puppet-module-keycloak#264]
Hi,

the script https://github.com/treydock/puppet-module-keycloak/blob/master/templates/kcadm-wrapper.sh.erb includes various variables without quoting them. This can be an issue because certain characters like `*` or `?` are evaluated by the shell upon execution.

Best,
Lukas

**Comment by treydock** [comment]
The fix will be released with 9.0.1 once Github Actions complete.
