### ISSUE TITLE
Custom `java_home` not actually used on RHEL-based distros

### ISSUE THREAD

**Issue by der-eismann** [treydock/puppet-module-keycloak#285]
Hey everyone, thanks for the cool project! It's working great so far, however I have an issue with the Java support in it.
When using the `java` class from puppet and passing the `java_home` property, all it does is [write it to `/etc/environment`](https://github.com/puppetlabs/puppetlabs-java/blob/main/manifests/config.pp#L47-L52), which [isn't read by systemd services](https://unix.stackexchange.com/a/473035). Using the `java_alternative` property makes it work, but that change is globally and could affect other services as well.

I would propose adding the `JAVA_HOME` env var to the [systemd service similarly to the `JAVA_OPTS`](https://github.com/treydock/puppet-module-keycloak/blob/master/templates/keycloak.service.erb#L13-L19), so the service is picking it up correctly. 

Also maybe it would make sense to add a `manage_jdk` flag to let the user configure the Java setup somewhere else?
WDYT?

**Comment by treydock** [comment]
@der-eismann For `manage_jdk` , would you want that to also turn off including the `java` module?  Currently you could set `java_declare_method => 'include'` which will only include the `java` class and let you control the parameter values for that class.
