### ISSUE TITLE
Module keeps recreating truststore file since upgrade to 11.0.0

### ISSUE THREAD

**Issue by promasu** [treydock/puppet-module-keycloak#302]
Since the upgrade from version 10.0.0 to 11.0.0 of this module we encounter an issue that keycloak is restarted every run because the truststore.jks is removed and newly created.

Our run logs:

```
notice | /Stage[main]/Keycloak::Config/File[/srv/keycloak/keycloak-22.0.3/conf/truststore.jks]/ensure | removed
info | /srv/keycloak/keycloak-22.0.3/conf | Scheduling refresh of Class[Keycloak::Service]
notice | /Stage[main]/Profile::Sso/Keycloak::Truststore::Host[example.com]/Java_ks[example.com]/ensure | created (corrective)
info | /Stage[main]/Profile::Sso/Keycloak::Truststore::Host[example.com]/Java_ks[example.com] | Scheduling refresh of Class[Keycloak::Service]
```

Our definition inside our puppet-files state:
```
keycloak::truststore::host { 'example.com':
    certificate => '/etc/ssl/certs/myca.pem',
}
```

I assume this behavior is because of the change here:
https://github.com/treydock/puppet-module-keycloak/commit/b99c30df52735adb69341f62432aeb36b6248b78#diff-b55cd2d4fee4ad88a9e21316ff2015c5579e8ec9bef7bc0fe5253262905fa702R26

Is this intended?
The documentation for `conf_dir_purge`: (https://github.com/treydock/puppet-module-keycloak/blob/master/manifests/init.pp#L54) states that only unmanaged files are purged.

Maybe the truststore.jks should be added to the ignore-list when specifying at least Keycloak::Truststore::Host?

**Comment by treydock** [comment]
The fix is in 11.0.1 of the Forge module release.
