### ISSUE TITLE
`service_java_opts` parameter not actually being used

### ISSUE THREAD

**Issue by danifr** [treydock/puppet-module-keycloak#49]
I'm trying to extend `$JAVA_OPTS` via the class param `service_java_opts` but it does not seem to work. 

I took a look at the code and it seems is defined but never used.
https://github.com/treydock/puppet-module-keycloak/search?q=service_java_opts&unscoped_q=service_java_opts

Thanks a lot.
Daniel.

**Comment by treydock** [comment]
Released in 3.4.0
