### ISSUE TITLE
Add support for standalone clustered mode

### ISSUE THREAD

**Issue by danifr** [treydock/puppet-module-keycloak#78]
Info about this mode: https://www.keycloak.org/docs/latest/server_installation/index.html#_standalone-ha-mode

I can prepare a PR for this. If I'm not mistaken, I think it is just a matter of changing the operating mode (standalone.xml or standalone-ha.xml) for the ExecStart in  `keycloak.service.erb`.

Am I missing something? Not sure if this
https://github.com/treydock/puppet-module-keycloak/blob/master/templates/config.cli.erb needs to be updated too.

**Comment by treydock** [comment]
I think you'd have to modify the service startup and also modify `config.cli.erb` to have this as first line: `embed-server --server-config=standalone-ha.xml`.  Maybe add a `mode` parameter to keycloak class that can either be `standalone` or `standalone-ha` with default being `standalone`.
