### ISSUE TITLE
Question about support for MySQL8

### ISSUE THREAD

**Issue by danifr** [treydock/puppet-module-keycloak#92]
Hi,

I'm playing around with Keycloak on MySQL8. I followed this blogpost https://pedrohosilva.wordpress.com/2019/08/11/04-configurando-banco-de-dados-mysql/ and I can confirm that it works.

Now, I'm trying to puppetize it but it did not work straight away. 

I provided the module with a custom `datasource_jar_source` pointing it to the new mysql-connector-java-8.0.XX.jar, but the service won't start.

After some investigation, I realized that this is the line that breaks it https://github.com/treydock/puppet-module-keycloak/blob/master/templates/config.cli.erb#L28

If I manually delete it from the standalone file, and restart the service, keycloak service starts OK

I don't understand very well the logic behind it.

`if (outcome != success)  .... `

Does the outcome always != success in my case?
Is there a simple way I can avoid that line being added to the standalone file?

Thanks a lot,
Daniel.

**Comment by treydock** [comment]
What does your Puppet code or manifest look like that is using this module?  The string that contains `(outcome != success)` is part of the config.cli that uses JBoss CLI to write out standalone.xml. The part you're referring to writes out part of the MySQL configs in standalone.xml if a certain XML element does not exist.

**Comment by danifr** [comment]
It looks like:
```
  class { 'keycloak':
    version                  => $version,
    proxy_https              => true,
    manage_datasource        => false,
    operating_mode           => $keycloak_operating_mode,
    datasource_driver        => $db_driver,
    datasource_host          => $db_host,
    datasource_port          => $db_port,
    datasource_dbname        => $db,
    datasource_username      => $db_username,
    datasource_password      => "$password,
    datasource_jar_source    => "${keycloak_config_dir}/mysql-connector-java-8.0.18.jar",
    service_environment_file => "${keycloak_base_dir}/keycloak.env",
  }
```

**Comment by treydock** [comment]
What does `/opt/keycloak/config.cli` look like for you?

The part that appears to be causing problems for you is setting the MySQL driver class name to `com.mysql.jdbc.jdbc2.optional.MysqlXADataSource`. Maybe this isn't valid for MySQL 8? The version of MySQL I've tested this with is 5.6 that ships with RHEL7 and MariaDB that ships with RHEL 8, and whatever version ships with Debian 9 and Ubuntu 18.04. 

This is what it looks like in standalone.xml or in your case would be standalone-ha.xml:

```
                    <driver name="mysql" module="com.mysql.jdbc">
                        <xa-datasource-class>com.mysql.jdbc.jdbc2.optional.MysqlXADataSource</xa-datasource-class>
                    </driver>
```

This is under `<subsystem xmlns="urn:jboss:domain:datasources:5.0">` -> datasources -> drivers.

If the default is invalid you can change with `mysql_datasource_class` parameter.

Looking here: https://dev.mysql.com/doc/connectors/en/connector-j-upgrading-to-8.0.html

Appears you need to set `mysql_datasource_class` to `com.mysql.cj.jdbc.MysqlXADataSource`.

**Comment by danifr** [comment]
Before closing this issue I'll leave here my keycloak + mysql8 puppet snippet.
``` 
 class { 'keycloak':
    version                  => '7.0.0',
    manage_datasource        => false,
    datasource_driver        => 'mysql',
    datasource_host          => 'mysql8.host.com',
    datasource_port          => 3306,
    datasource_dbname        => 'keycloak',
    datasource_username      => 'keycloak',
    datasource_password      => 'supersecret',
    datasource_jar_source    => "/opt/keycloak/mysql-connector-java-8.0.18.jar",
    datasource_xa_class      => 'com.mysql.cj.jdbc.MysqlXADataSource',
  }
```
You need to create the DB manually.
During the creation of the database don't forget to set the right `chararter set` and `collate`
```
CHARACTER SET utf8 COLLATE utf8_unicode_ci;`
```
Follow: https://pedrohosilva.wordpress.com/2019/08/11/04-configurando-banco-de-dados-mysql/ for more info.
